parameters:
  loss_weights:
    # W-part
    L_x: 10.0
    L_x_huber: 0.5
    # lep-part
    L_y: 0.1
    # N(0, 1) sampling part
    L_z: 10.0
    # padding part (if any)
    L_pad: 1.0
    L_pad_noise: 0.1
    # monitoring losses
    L_x_gen: 0.0
  batch_size: 256
  epochs: 1024
  learning_rate: 1.0e-4
  num_blocks: 8
  # observed variables dimension: pos/neg lepton px, py, eta, log(E)
  obs_dim: 8
  # number of lacking constraints (two neutrinos are massless)
  lack_dim: 8
  # dataloader settings (set num_workers > 0 only if stable)
  num_workers: 6
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 4

paths:
  data_path: "/root/data/danning_h5/ypeng/mc20_qe_v4_recotruth_merged.h5"
  project_name: "hww_inn_regressor-lep"
  ckpt_path: "/root/work/ww-flow/logs/"
